[[plugins]]
repo = 'Shougo/dein.vim'

# 表示
[[plugins]]
repo = 'Shougo/vimfiler'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

# 補完
[[plugins]]
repo = 'Shougo/neocomplete.vim'

[[plugins]]
repo = 'alpaca-tc/vim-endwise.git'

# 検索
[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'szw/vim-tags'

# tool
[[plugins]]
repo = 'tell-k/vim-browsereload-mac'

[[plugins]]
repo = 'ngmy/vim-rubocop'

[[plugins]]
repo = 'scrooloose/syntastic'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'thinca/vim-ref'

[[plugins]]
repo = 'yuku-t/vim-ref-ri'

[[plugins]]
repo = 'szw/vim-tags'

# syntax
[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'plasticboy/vim-markdown'

[[plugins]]
repo = 'kchmck/vim-coffee-script'

[[plugins]]
repo = 'thoughtbot/vim-rspec'

[[plugins]]
repo = 'slim-template/vim-slim'

[[plugins]]
repo = 'othree/html5.vim'

[[plugins]]
repo = 'gisphm/vim-gitignore'
